
services:
  reframe:
    build: .
    image: reframe:pgolovko
    container_name: reframe
    ports:
      - "8080:8080"
    volumes:
      - ./media/uploads:/app/uploads
      - ./media/exports:/app/exports
      - ./media/fonts:/app/fonts
      - ./media/models:/app/models
    restart: unless-stopped
    # Uncomment the following lines to enable AMD/Intel GPU support in Docker via VAAPI
    devices:
      - /dev/dri:/dev/dri
